project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - FinalProject.qmd
    - calvary_mem_proj.qmd
    - MagicCubeProject.qmd
    - excel_personel_budget_proj.qmd
    - projects_page.qmd

resources: 
  - videos/ccmp2.mp4
  - videos/ebp.mp4

website:
  title: "Caleb Vander Wall"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: C.V.
        href: index.qmd
      - text: Projects
        href: projects_page.qmd
format:
  html:
    
    backgroundcolor: "#FFFFFF"
    mainfont: "helvetica"
    theme: [cosmo, styles.scss]

