project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - FinalProject.qmd
    - calvary_mem_proj.qmd
    - MagicCubeProject.qmd

resources: 
  - videos/ccmp2.mp4

website:
  title: "Caleb Vander Wall"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: C.V.
        href: index.qmd
      - text: Chiefs Data Project
        href: FinalProject.qmd
      - text: Calvary Church Membership Project
        href: calvary_mem_proj.html
      - text: Magic Cube Project
        href: MagicCubeProject.qmd
format:
  html:
    
    backgroundcolor: "#FFFFFF"
    mainfont: "helvetica"
    theme: [cosmo, styles.scss]

